### ISSUE TITLE
J'ai accès à une liste de toutes les actions d'une mesure

### ISSUE THREAD

**Issue by annepoirot** [labels-transition/produit#25]
1. On a besoin d'une 1ere maquette (schéma de hiérarchisation) sans détails

2. On doit choisir un URL d'accès

3. On se base sur le référentiel Cit'ergie 2021

4. On commence par le nom de la mesure 1.1.1: Définir la vision, les objectifs et la stratégie Climat-Air-Energie

5. Au sein des actions on voudrait :
    - le nom des actions
    - l'ordre des actions reste le même que dans le doc

**Comment by Ynote** [comment]
Les maquettes proposées par @maiwann : 
![IMG_20210119_153234](https://user-images.githubusercontent.com/548778/105053821-a9b5cb80-5a71-11eb-8f4c-2d49fcd25e63.jpg)
![IMG_20210119_151512](https://user-images.githubusercontent.com/548778/105053825-aa4e6200-5a71-11eb-82da-8c9523c16223.jpg)

**Comment by Ynote** [comment]
La page est disponible sur http://staging.territoiresentransitions.fr/mesure_1.1.1.html.
